# Generated by Django 3.0.4 on 2020-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_site_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_user',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
