# Generated by Django 3.0.4 on 2020-03-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_site_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupnotification',
            name='notification',
        ),
        migrations.AddField(
            model_name='groupnotification',
            name='color',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupnotification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupings', to='monitor.Group'),
        ),
    ]
