# Generated by Django 3.0.4 on 2020-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200324_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnotification',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
