# Generated by Django 3.0.4 on 2020-04-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20200324_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userskill',
            old_name='yearsOfExperience',
            new_name='years_of_experience',
        ),
    ]
