# Generated by Django 3.0.4 on 2020-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_requesttogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttogroup',
            name='status',
            field=models.CharField(choices=[('AC', 'ACCEPT'), ('PG', 'PENDING')], default='AC', max_length=2),
        ),
    ]
