# Generated by Django 3.0.4 on 2020-04-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_requesttogroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttogroup',
            name='status',
            field=models.CharField(choices=[('AC', 'ACCEPT'), ('PG', 'PENDING'), ('CL', 'CLOSED')], default='AC', max_length=2),
        ),
    ]
