# Generated by Django 3.0.4 on 2020-04-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20200406_2039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set(),
        ),
    ]
