# Generated by Django 3.0.4 on 2020-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20200406_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_user',
            name='description',
            field=models.TextField(blank=True, default=' Eager to teach things', null=True),
        ),
    ]
